# Generated by Django 2.1 on 2022-07-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApellidoPaterno', models.CharField(max_length=60)),
                ('ApellidoMaterno', models.CharField(default='-', max_length=60)),
                ('Nombres', models.CharField(max_length=60)),
                ('Direccion', models.CharField(default='-', max_length=100)),
                ('DNI', models.CharField(default='-', max_length=8, unique=True)),
                ('FechaNacimiento', models.DateField()),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('Estado', models.CharField(choices=[('A', 'Activo'), ('R', 'Retirado'), ('E', 'Egresado')], default='A', max_length=1)),
            ],
        ),
    ]
