# Generated by Django 2.1 on 2022-07-27 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Matricula', '0001_initial'),
        ('Docente', '0001_initial'),
        ('Curso', '0001_initial'),
        ('PeriodoAcademico', '0001_initial'),
        ('Competencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nota', models.CharField(default='-', max_length=100)),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curso.Curso')),
                ('Docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docente.Docente')),
                ('Matricula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Matricula.Matricula')),
                ('PAcademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PeriodoAcademico.PAcademico')),
            ],
        ),
        migrations.CreateModel(
            name='NotasComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nota', models.CharField(default='-', max_length=250)),
                ('Competencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Competencias.Competencias')),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curso.Curso')),
                ('Docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docente.Docente')),
                ('Matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matricula.Matricula')),
                ('PAcademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PeriodoAcademico.PAcademico')),
            ],
        ),
        migrations.CreateModel(
            name='SettingNotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Propiedad', models.CharField(default='-', max_length=100)),
                ('Valor', models.BooleanField(default=False)),
            ],
        ),
    ]
