# Generated by Django 2.1 on 2022-07-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodCurso', models.CharField(max_length=20, unique=True)),
                ('Orden', models.IntegerField(default=1)),
                ('Nombre', models.CharField(max_length=80)),
                ('Tipo', models.CharField(choices=[('CURSO', 'CURSO'), ('ACTITUDINAL', 'ACTITUDINAL'), ('INASISTENCIAS', 'INASISTENCIAS'), ('DEL PADRE DE FAMILIA', 'DEL PADRE DE FAMILIA'), ('APRECIACIÓN DEL TUTOR', 'APRECIACIÓN DEL TUTOR'), ('--', '--')], default='-', max_length=60)),
                ('Grados', models.CharField(default='-', max_length=60)),
                ('Nivel', models.CharField(choices=[('PRIM', 'PRIM'), ('SEC', 'SEC')], default='PRIM', max_length=60)),
            ],
        ),
    ]
