# Generated by Django 2.1 on 2022-07-27 16:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alumno', '0001_initial'),
        ('AnoAcademico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grado', models.CharField(choices=[('1PRIM', '1PRIM'), ('2PRIM', '2PRIM'), ('3PRIM', '3PRIM'), ('4PRIM', '4PRIM'), ('5PRIM', '5PRIM'), ('6PRIM', '6PRIM'), ('1SEC', '1SEC'), ('2SEC', '2SEC'), ('3SEC', '3SEC'), ('4SEC', '4SEC'), ('5SEC', '5SEC')], default='--', max_length=60)),
                ('Seccion', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='A', max_length=1)),
                ('FechaMat', models.DateField(default=django.utils.timezone.now)),
                ('Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.Alumno')),
                ('AnoAcademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnoAcademico.AnoAcademico')),
            ],
        ),
    ]
