# Generated by Django 2.1 on 2022-07-27 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenciaCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Competencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('PRIM', 'PRIM'), ('SEC', 'SEC')], default='PRIM', max_length=10)),
                ('nombre_competencia', models.CharField(default='', max_length=250)),
                ('Orden', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='competenciacurso',
            name='Competencias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Competencias.Competencias'),
        ),
        migrations.AddField(
            model_name='competenciacurso',
            name='Curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curso.Curso'),
        ),
    ]
