"""
Django settings for colegio project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1o^2hv64-t#7)p583)&2b2@-&@cnx%m7ia8pyv251ub(jt^^0j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition
MESSAGE_STORAGE='django.contrib.messages.storage.session.SessionStorage'
SESSION_COOKIE_AGE = 50000
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # 'livereload',
    'django.contrib.staticfiles',

    'colegio.Apps.Notas',
    'colegio.Apps.Matricula',
    'colegio.Apps.Apoderado',
    'colegio.Apps.PeriodoAcademico',
    'colegio.Apps.AnoAcademico',
    'colegio.Apps.Curso',
    'colegio.Apps.Alumno',
    'colegio.Apps.Docente',
    'colegio.Apps.DocenteCurso',
    'colegio.Apps.Login',
    'colegio.Apps.Home',
    'colegio.Apps.Nivel',
    'colegio.Apps.Grado',
    'colegio.Apps.Seccion',
    'colegio.Apps.TempDatos',
    'colegio.Apps.Usuario',
    'colegio.Apps.OtrasOpciones',
    'colegio.Apps.BuscarNotas',
    'colegio.Apps.AvanceNotas',
    'colegio.Apps.AvanceTempDatos',
    'colegio.Apps.Competencias',
    'colegio.Apps.LibretaAvance',
    'colegio.Apps.Aulas',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'livereload.middleware.LiveReloadScript'
]

ROOT_URLCONF = 'colegio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'colegio.Apps.context_proccesors.data_templates'

            ],
        },
    },
]

WSGI_APPLICATION = 'colegio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'dbcolegio002',
        'USER':'postgres',
        'PASSWORD':'123456',
        'HOST':'localhost',
        'PORT':'5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'staticfiles'
STATICFILES_DIRS = (os.path.join(BASE_DIR,'static'),)
MEDIA_ROOT = os.path.join(BASE_DIR,'static')
LOGIN_URL='/login/'# esto fue agregado para corregir el por defecto asignado por el sistema accounts/login
LOGIN_REDIRECT_URL = '/'#aqui deberia ser home pero le quite para que sea la raiz el home
LOGOUT_REDIRECT_URL = '/login'