# Generated by Django 2.1 on 2022-07-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seccion', '0001_initial'),
        ('Grado', '0001_initial'),
        ('AnoAcademico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnoAcademico', models.ForeignKey(on_delete='CASCADE', to='AnoAcademico.AnoAcademico')),
                ('Grado', models.ForeignKey(on_delete='CASCADE', to='Grado.Grado')),
                ('Seccion', models.ForeignKey(on_delete='CASCADE', to='Seccion.Seccion')),
            ],
        ),
    ]
